/*
 * DIO_Configurations.h
 *
 *  Created on: ???/???/????
 *      Author: Hesha
 */

#ifndef INCLUDE_MCAL_DIO_DIO_CONFIGURATIONS_H_
#define INCLUDE_MCAL_DIO_DIO_CONFIGURATIONS_H_

#define PORTA 0
#define PORTB 1
#define PORTC 2
#define PORTD 3

#define PORT_A 0
#define PORT_B 1
#define PORT_C 2
#define PORT_D 3

#define PIN0 0
#define PIN1 1
#define PIN2 2
#define PIN3 3
#define PIN4 4
#define PIN5 5
#define PIN6 6
#define PIN7 7

#define OUTPUT_PIN 1
#define INPUT_PIN 0

#define PIN_HIGH 1
#define PIN_LOW 0

#define PIN_PULLUP 1
#define PIN_FLOATING 0

//Direction :-
//		OUTPUT_PIN - INPUT_PIN

#define PORTA_PIN0_DIRECTION INPUT_PIN
#define PORTA_PIN1_DIRECTION INPUT_PIN
#define PORTA_PIN2_DIRECTION INPUT_PIN
#define PORTA_PIN3_DIRECTION INPUT_PIN
#define PORTA_PIN4_DIRECTION INPUT_PIN
#define PORTA_PIN5_DIRECTION OUTPUT_PIN
#define PORTA_PIN6_DIRECTION OUTPUT_PIN
#define PORTA_PIN7_DIRECTION OUTPUT_PIN

#define PORTB_PIN0_DIRECTION OUTPUT_PIN
#define PORTB_PIN1_DIRECTION OUTPUT_PIN
#define PORTB_PIN2_DIRECTION OUTPUT_PIN
#define PORTB_PIN3_DIRECTION OUTPUT_PIN
#define PORTB_PIN4_DIRECTION OUTPUT_PIN
#define PORTB_PIN5_DIRECTION OUTPUT_PIN
#define PORTB_PIN6_DIRECTION OUTPUT_PIN
#define PORTB_PIN7_DIRECTION OUTPUT_PIN

#define PORTC_PIN0_DIRECTION OUTPUT_PIN
#define PORTC_PIN1_DIRECTION OUTPUT_PIN
#define PORTC_PIN2_DIRECTION OUTPUT_PIN
#define PORTC_PIN3_DIRECTION OUTPUT_PIN
#define PORTC_PIN4_DIRECTION OUTPUT_PIN
#define PORTC_PIN5_DIRECTION OUTPUT_PIN
#define PORTC_PIN6_DIRECTION OUTPUT_PIN
#define PORTC_PIN7_DIRECTION OUTPUT_PIN

#define PORTD_PIN0_DIRECTION OUTPUT_PIN
#define PORTD_PIN1_DIRECTION OUTPUT_PIN
#define PORTD_PIN2_DIRECTION OUTPUT_PIN
#define PORTD_PIN3_DIRECTION OUTPUT_PIN
#define PORTD_PIN4_DIRECTION OUTPUT_PIN
#define PORTD_PIN5_DIRECTION OUTPUT_PIN
#define PORTD_PIN6_DIRECTION OUTPUT_PIN
#define PORTD_PIN7_DIRECTION OUTPUT_PIN

//VALUE :-
//		PIN_HIGH - PIN_LOW
//		PIN_PULLUP - PIN_FLOATING

#define PORTA_PIN0_VALUE PIN_FLOATING
#define PORTA_PIN1_VALUE PIN_FLOATING
#define PORTA_PIN2_VALUE PIN_FLOATING
#define PORTA_PIN3_VALUE PIN_FLOATING
#define PORTA_PIN4_VALUE PIN_FLOATING
#define PORTA_PIN5_VALUE PIN_LOW
#define PORTA_PIN6_VALUE PIN_LOW
#define PORTA_PIN7_VALUE PIN_LOW

#define PORTB_PIN0_VALUE PIN_LOW
#define PORTB_PIN1_VALUE PIN_LOW
#define PORTB_PIN2_VALUE PIN_LOW
#define PORTB_PIN3_VALUE PIN_LOW
#define PORTB_PIN4_VALUE PIN_LOW
#define PORTB_PIN5_VALUE PIN_LOW
#define PORTB_PIN6_VALUE PIN_LOW
#define PORTB_PIN7_VALUE PIN_LOW

#define PORTC_PIN0_VALUE PIN_HIGH
#define PORTC_PIN1_VALUE PIN_HIGH
#define PORTC_PIN2_VALUE PIN_LOW
#define PORTC_PIN3_VALUE PIN_LOW
#define PORTC_PIN4_VALUE PIN_LOW
#define PORTC_PIN5_VALUE PIN_LOW
#define PORTC_PIN6_VALUE PIN_LOW
#define PORTC_PIN7_VALUE PIN_LOW

#define PORTD_PIN0_VALUE PIN_HIGH
#define PORTD_PIN1_VALUE PIN_HIGH
#define PORTD_PIN2_VALUE PIN_HIGH
#define PORTD_PIN3_VALUE PIN_HIGH
#define PORTD_PIN4_VALUE PIN_HIGH
#define PORTD_PIN5_VALUE PIN_HIGH
#define PORTD_PIN6_VALUE PIN_PULLUP
#define PORTD_PIN7_VALUE PIN_HIGH







#endif /* INCLUDE_MCAL_DIO_DIO_CONFIGURATIONS_H_ */
